//go:build linux

package main

import (
	"bufio"
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"testing"
	"time"

	"golang.org/x/crypto/ssh"
)

func testGateway(t *testing.T, script string, serverURL string) (*gateway, context.CancelFunc, <-chan error) {
	t.Helper()
	directory := t.TempDir()
	_, privateKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	encoded, err := x509.MarshalPKCS8PrivateKey(privateKey)
	if err != nil {
		t.Fatal(err)
	}
	hostKey := filepath.Join(directory, "host-key")
	if err := os.WriteFile(hostKey, pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: encoded}), 0o600); err != nil {
		t.Fatal(err)
	}
	client := filepath.Join(directory, "client")
	if err := os.WriteFile(client, []byte("#!/bin/sh\n"+script), 0o700); err != nil {
		t.Fatal(err)
	}
	cfg := config{
		ListenAddress:       "127.0.0.1:0",
		HealthAddress:       "127.0.0.1:0",
		HostKeyPath:         hostKey,
		ClientPath:          client,
		ServerURL:           serverURL,
		MaxConnections:      8,
		MaxConnectionsPerIP: 8,
		MaxSessions:         4,
		MaxSessionsPerIP:    4,
		AttemptsPerMinute:   100,
		HandshakeTimeout:    2 * time.Second,
		SessionTimeout:      time.Minute,
		ShutdownGrace:       200 * time.Millisecond,
	}
	app, _, err := newGateway(cfg)
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	done := make(chan error, 1)
	go func() { done <- app.run(ctx) }()
	deadline := time.Now().Add(2 * time.Second)
	for app.listener == nil && time.Now().Before(deadline) {
		time.Sleep(10 * time.Millisecond)
	}
	if app.listener == nil {
		cancel()
		t.Fatal("gateway did not listen")
	}
	return app, cancel, done
}

func dialGateway(t *testing.T, address, user string) *ssh.Client {
	t.Helper()
	client, err := ssh.Dial("tcp", address, &ssh.ClientConfig{
		User:            user,
		HostKeyCallback: ssh.InsecureIgnoreHostKey(), // Ephemeral key generated by this test.
		Timeout:         2 * time.Second,
	})
	if err != nil {
		t.Fatal(err)
	}
	return client
}

func stopTestGateway(t *testing.T, cancel context.CancelFunc, done <-chan error) {
	t.Helper()
	cancel()
	select {
	case err := <-done:
		if err != nil {
			t.Fatal(err)
		}
	case <-time.After(3 * time.Second):
		t.Fatal("gateway did not stop")
	}
}

func TestGatewayRunsOnlyPTYGameShellAndPropagatesBoundedResize(t *testing.T) {
	app, cancel, done := testGateway(t, `
trap 'stty size' WINCH
printf 'READY\r\n'
while :; do
  IFS= read -r line || continue
  printf 'ECHO:%s\r\n' "$line"
done
`, "unused")
	defer stopTestGateway(t, cancel, done)

	client := dialGateway(t, app.listener.Addr().String(), "termenor")
	defer client.Close()
	session, err := client.NewSession()
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()
	input, err := session.StdinPipe()
	if err != nil {
		t.Fatal(err)
	}
	output, err := session.StdoutPipe()
	if err != nil {
		t.Fatal(err)
	}
	if err := session.RequestPty("xterm-256color", 24, 80, ssh.TerminalModes{ssh.ECHO: 0}); err != nil {
		t.Fatal(err)
	}
	if err := session.Shell(); err != nil {
		t.Fatal(err)
	}
	reader := bufio.NewReader(output)
	if line, err := reader.ReadString('\n'); err != nil || !strings.Contains(line, "READY") {
		t.Fatalf("missing game client output: %q %v", line, err)
	}
	if err := session.WindowChange(1, 500); err != nil {
		t.Fatal(err)
	}
	deadline := time.Now().Add(2 * time.Second)
	for time.Now().Before(deadline) {
		line, err := reader.ReadString('\n')
		if err != nil {
			t.Fatal(err)
		}
		if strings.Contains(line, "20 240") {
			break
		}
		if time.Now().After(deadline) {
			t.Fatalf("bounded resize not observed, last line %q", line)
		}
	}
	if _, err := fmt.Fprintln(input, "ping"); err != nil {
		t.Fatal(err)
	}
	for {
		line, err := reader.ReadString('\n')
		if err != nil {
			t.Fatal(err)
		}
		if strings.Contains(line, "ECHO:ping") {
			break
		}
	}
}

func TestGatewayRejectsExecSubsystemForwardingAgentsAndWrongUser(t *testing.T) {
	app, cancel, done := testGateway(t, "exec cat\n", "unused")
	defer stopTestGateway(t, cancel, done)
	address := app.listener.Addr().String()
	execClient := dialGateway(t, address, "termenor")
	defer execClient.Close()
	execSession, err := execClient.NewSession()
	if err != nil {
		t.Fatal(err)
	}
	if err := execSession.Run("id"); err == nil {
		t.Fatal("arbitrary exec request was accepted")
	}
	_ = execSession.Close()

	subsystemClient := dialGateway(t, address, "termenor")
	defer subsystemClient.Close()

	subsystemSession, err := subsystemClient.NewSession()
	if err != nil {
		t.Fatal(err)
	}
	if err := subsystemSession.RequestSubsystem("sftp"); err == nil {
		t.Fatal("SFTP subsystem was accepted")
	}
	if ok, err := subsystemSession.SendRequest("auth-agent-req@openssh.com", true, nil); err != nil || ok {
		t.Fatalf("agent forwarding accepted: ok=%v err=%v", ok, err)
	}
	_ = subsystemSession.Close()

	forwardClient := dialGateway(t, address, "termenor")
	defer forwardClient.Close()

	forwarded, err := forwardClient.Dial("tcp", "127.0.0.1:1")
	if err == nil {
		_ = forwarded.Close()
		t.Fatal("TCP forwarding channel was accepted")
	}

	wrongUser := dialGateway(t, address, "root")
	defer wrongUser.Close()
	if session, err := wrongUser.NewSession(); err == nil {
		_ = session.Close()
		t.Fatal("non-termenor transport identity opened a session")
	}
}

func TestGatewayReapsClientProcessGroupOnDisconnect(t *testing.T) {
	pidFile := filepath.Join(t.TempDir(), "client.pid")
	app, cancel, done := testGateway(t, `
printf '%s' "$$" > "$2"
trap 'exit 0' HUP INT TERM
while :; do sleep 1; done
`, pidFile)
	defer stopTestGateway(t, cancel, done)

	client := dialGateway(t, app.listener.Addr().String(), "termenor")
	session, err := client.NewSession()
	if err != nil {
		t.Fatal(err)
	}
	if err := session.RequestPty("xterm", 24, 80, nil); err != nil {
		t.Fatal(err)
	}
	if err := session.Shell(); err != nil {
		t.Fatal(err)
	}
	deadline := time.Now().Add(2 * time.Second)
	var pid int
	for time.Now().Before(deadline) {
		contents, err := os.ReadFile(pidFile)
		if err == nil {
			pid, err = strconv.Atoi(string(contents))
			if err != nil {
				t.Fatal(err)
			}
			break
		}
		time.Sleep(20 * time.Millisecond)
	}
	if pid == 0 {
		t.Fatal("client process did not start")
	}
	_ = client.Close()

	deadline = time.Now().Add(3 * time.Second)
	for time.Now().Before(deadline) {
		err := syscall.Kill(pid, 0)
		if errors.Is(err, syscall.ESRCH) {
			return
		}
		time.Sleep(20 * time.Millisecond)
	}
	if process, err := os.FindProcess(pid); err == nil {
		_ = process.Kill()
	}
	t.Fatal("client process survived SSH disconnect")
}

func TestGatewayHealthIsLoopbackHTTP(t *testing.T) {
	if host, _, err := net.SplitHostPort("127.0.0.1:3001"); err != nil || host != "127.0.0.1" {
		t.Fatalf("invalid health binding: %v", err)
	}
}
